finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/<int:finch_id>/', views.finches_detail,name='detail' ),
    path('finches/create/', views.FinchCreate.as_view(),
    name='finches_create'),
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
     path('finches/<int:finch>/assoc_habitat/<int:habitat_id>', views.assoc_habitat, name='assoc_habitat'),
    path('cats/<int:finch_id>/unassoc_habitat/<int:habitat_id>', views.unassoc_habitat, name='unassoc_habitat'),
    path('habitats/', views.HabitatList.as_view(), name='habitats_index'),
    path('habitats/<int:pk>/', views.HabitatDetail.as_view(), name='habitats_detail'),
    path('habitats/create/', views.HabitatCreate.as_view(), name='habitats_create'),
    path('habitats/<int:pk>/update/', views.HabitatUpdate.as_view(), name='habitats_update'),
    path('habitats/<int:pk>/delete/', views.HabitatDelete.as_view(), name='habitats_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.
class Habitat(models.Model):
  name = models.CharField(max_length=100)
  description = models.CharField(max_length=250)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('habitats_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    name = models.CharField(max_length=100)
    s_name = models.CharField(max_length=100)
    origin = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    habitats = models.ManyToManyField(Habitat)
    
    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})

class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    finch = models.ForeignKey(
        Finch, 
        on_delete=models.CASCADE
        )

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    # change the default sort
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .models import Finch, Habitat
from .forms import FeedingForm
# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', {
        'finches': finches
    })

def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    id_list = finch.habitats.all().values_list('id')
    habitat_finch_doesnt_have = Habitat.objects.exclude(id__in=id_list)
    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', {
        'finch': finch, 'feeding_form': feeding_form
    })

def add_feeding(request, finch_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.finch_id = finch_id
        new_feeding.save()
    return redirect('detail', finch_id=finch_id)

def assoc_habitat(request, finch_id, habitat_id):
    Finch.objects.get(id=finch_id).habitats.add(habitat_id)
    return redirect('detail', finch_id=finch_id)

def unassoc_habitat(request, finch_id, habitat_id):
    Finch.objects.get(id=finch_id).habitats.remove(habitat_id)
    return redirect('detail', finch_id=finch_id)

class FinchCreate(CreateView):
    model = Finch
    fields = ['name', 's_name', 'origin', 'description']

class FinchUpdate(UpdateView):
    model = Finch
    fields = ['name', 's_name', 'origin', 'description']

class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches'

class HabitatList(ListView):
    model = Habitat

class HabitatDetail(DetailView):
    model = Habitat

class HabitatCreate(CreateView):
    model = Habitat
    fields = '__all__'
class HabitatUpdate(UpdateView):
    model = Habitat
    fields = ['name', 'description']

class HabitatDelete(DeleteView):
    model = Habitat
    success_url = '/habitats'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

  <h1>This is About Page</h1>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Finches Collection</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="../static/img/noun-blackbird-1098360.svg" alt="Logo" width="30" height="24">Finches</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">All Finches</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'finches_create' %}">Add Finches</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'habitats_index' %}">All Habitats</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'habitats_create' %}">Add Habitat</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">about</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
   <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
   <div class="right">All Rights Reserved, &copy; 2023 Finches Collector &nbsp;</div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ finch.name }}</span>
    <p>Scientific Name: {{ finch.s_name }}</p>
    <p>Origin: {{ finch.origin }}</p>
    <p>Description: {{ finch.description|linebreaks }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'finches_update' finch.id%}">Edit</a>
    <a href="{% url 'finches_delete' finch.id%}">Delete</a>
  </div>
  <div>
    <form action="{% url 'add_feeding' finch.id %}" method="POST">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>
    <table>
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}|</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Habitats</h3>
    {% if finch.habitats.count %}
      {% for habitat in finch.habitats.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              Habitats: {{ habitat.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_habitat' finch.id habitat.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>Not sure about Habitats yet</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Known Habitats</h3>
    {% if habitats.count %}
      {% for habitat in habitats.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              Habitats: {{ habitat.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_habitat' finch.id habitat.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>Already know about {{finch.name}}'s habitats</h5>
    {% endif %}
  </div>
</div> 

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>All Finches</h1>
{% for finch in finches %}
  <a href="{% url 'detail' finch.id %}">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Origin: {{ finch.origin }}</p>
        <p>Description: {{ finch.description|linebreaks }}</p>
      </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

  <h1>Home Page</h1>

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">
        {{object.name}}    
    </span></h1>
{% else %}
    <h1>Add Finch</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/habitat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Habitat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'habitats_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/habitat_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Habitat Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ habitat.name }}</span>
        <p>Description: {{ habitat.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'habitats_update' habitat.id %}">Edit</a>
        <a href="{% url 'habitats_delete' habitat.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/habitat_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Habitat</h1>
{% endif %}

<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/habitat_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Habitat List</h1>

{% for habitat in habitat_list %}
  <a href="{% url 'habitats_detail' habitat.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ habitat.name }}</span>
            <p>description: {{ habitat.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}